import json
fixes = {
"11627|text": "<b>Erzwungen</b> - Nachdem du 1 oder mehr Karten von der Oberseite des Begegnungsdecks ablegst, während du an der Erhabenen Passage bist: Der nächstgelegene spielbereite Nicht-[[Elite]]-Gegner löst sich von jedem Ermittler und bewegt sich zu diesem Ort.",
"11628|subname": "Archiv der Geschichte",
"11628|text": "Die Leuchtenden Archive bekommen +1 Schleier für jede [[Glyphe]]-Karte an oder an ihnen angehängt.\n[fast] Gib X Aktionen aus (mindestens 1): Durchsuche den Ablagestapel des Begegnungsdecks nach bis zu X [[Glyphe]]-Karten und ziehe sie, eine nach der anderen.\n[action]: <b>Bewegen.</b> Bewege dich zu einem enthüllten [[Durchgang]]-Ort.",
"11629|subname": "Archiv der Erinnerung",
"11629|text": "<b>Erzwungen</b> - Wenn die Ermittlungsphase endet und sich Hinweise auf den Leuchtenden Archiven befinden: Mische jede an diesen Ort angehängte [[Glyphe]]-Verratskarte in das Begegnungsdeck zurück.\n[action][action]: Durchsuche den Ablagestapel des Begegnungsdecks nach einer [[Glyphe]]-Karte und ziehe sie.",
"11630|subname": "Beobachter der Träume",
"11630|text": "Falls die Ermittler 10 oder mehr Glyphen übersetzt haben, erhält dieser Gegner Erbarmungslos.\n<b>Erzwungen</b> - Wenn du diesen Gegner besiegst, entdecke diese Glyphe:\n[tdc_rune_k]\nNotiere in deinem Kampagnenlogbuch „Träume“ unter [tdc_rune_k] im Glyphenprotokoll. Diese Glyphe wurde übersetzt.",
"11631|subname": "Weberin der Albträume",
"11631|text": "Falls die Ermittler 10 oder mehr Glyphen übersetzt haben, erhält dieser Gegner Alarmiert und Zurückschlagen.\n<b>Erzwungen</b> - Wenn du diesen Gegner besiegst, entdecke diese Glyphe:\n[tdc_rune_j]\nNotiere in deinem Kampagnenlogbuch „Schlaf“ unter [tdc_rune_j] im Glyphenprotokoll. Diese Glyphe wurde übersetzt.",
"11639|text": "<b>Enthüllung</b> - Lege eine [willpower]-Probe (3) ab. Für jeden Punkt, um den die Probe misslingt, musst du entweder 1 Horror erleiden oder die Flutstufe deines Ortes erhöhen.\n[action] Lege 1 [per_investigator] Hinweise ab, als Gruppe: Du entdeckst diese Glyphe:\n[tdc_rune_b]\nNotiere in deinem Kampagnenlogbuch „Pflanze“ unter [tdc_rune_b] im Glyphenprotokoll. Diese Glyphe wurde übersetzt.",
"11640|text": "<b>Enthüllung</b> - Lege eine [agility]-Probe (3) ab. Falls die Probe misslingt, bringe die beiseitegelegte Verratskarte Jagender Parasit in deiner Bedrohungszone ins Spiel.\n[reaction] Nachdem du den letzten Hinweis an diesem Ort entdeckst: Du entdeckst diese Glyphe:\n[tdc_rune_c]\nNotiere in deinem Kampagnenlogbuch „Älteres Wesen“ unter [tdc_rune_c] im Glyphenprotokoll. Diese Glyphe wurde übersetzt.",
"11640b|text": "<blockquote><i>Du legst die Hand auf das flimmernde Energiefeld und spürst ein Kribbeln in deinen Fingerspitzen. Es ist, als ob das Feld die Form deiner Hand erkennt und sich dir öffnet. Auf der anderen Seite liegt eine Weite aus strahlendem, lebendem Grün. Nach all den Meilen aus Stein und Salz ist das hier der wunderlichste Anblick von allen. Du blickst zu deinen Gefährten, und ihr rückt zusammen, um das Wunder zu betrachten. Ihr habt es tatsächlich geschafft: Der Garten Eden, neu geboren.</i></blockquote>\nDu entdeckst diese Glyphe:\n[tdc_rune_c]\nNotiere in deinem Kampagnenlogbuch „Älteres Wesen“ unter [tdc_rune_c] im Glyphenprotokoll. Diese Glyphe wurde übersetzt. Füge diese Karte dem Siegespunktestapel hinzu.",
"11647|text": "<b>Erzwungen</b> - Nachdem du deinen Zug an diesem Ort beendet hast: Du musst entweder 1 zufällige Karte von deiner Hand ablegen oder 1 Schaden erleiden.\n[fast] Während deines Zuges, gib 1 Hinweis aus: Wähle einen Gegner an einem [[Gipfel]]-Ort bis zu 3 Verbindungen entfernt. Tausche die Plätze mit dem gewählten Gegner, wobei du den <b>Erzwungen</b>-Effekt seines Ortes ignorierst.",
"11648|text": "<b>Erzwungen</b> - Nachdem du deinen Zug an diesem Ort beendet hast: Lege eine [agility]-Probe (X) ab, wobei X die Anzahl der Ermittler an diesem Ort ist. Falls die Probe misslingt, lege das Hängende Schiff ab <i>(oben auf das Gipfeldeck)</i>.\n[action] Jeder Ermittler an diesem Ort gibt 1 Hinweis aus: Schiebe das Hängende Schiff einmal in einen angrenzenden offenen Himmel.",
"11649|text": "<b>Erzwungen</b> - Nachdem du diesen Ort enthüllst: Lege eine [agility]-Probe (1) ab. Falls die Probe misslingt, durchsuche das Begegnungsdeck und den Ablagestapel nach einem [[Monster]]-Gegner und erschaffe ihn, mit dir in einen Kampf verwickelt.\n[action]: Bringe das beiseitegelegte Himmelsrelikt [tdc_rune_f] unter deiner Kontrolle ins Spiel.",
"11661|text": "Du kannst keine Fähigkeiten auf [[Feuerwaffe]]-Vorteilskarten auslösen, während du an den Magnetischen Turmspitzen bist.\n[action] Jeder Ermittler an diesem Ort gibt 1 Hinweis aus: Wähle einen offenen Himmel bis zu 2 Felder entfernt. Tausche die Magnetischen Turmspitzen mit dem gewählten offenen Himmel. (Gruppenlimit einmal pro Spiel.)",
"11662|text": "Falls das Glyphen-Planetarium [tdc_rune_d] das Spiel verlassen würde, lege es beiseite, außerhalb des Spiels <i>(oder auf den Siegespunktestapel, falls sich keine Hinweise auf ihm befinden)</i>.\n<b>Erzwungen</b> - Wenn du diesen Ort betreten würdest und du die Obsidianklaue nicht kontrollierst: Du musst entweder 1 Hinweis ausgeben oder eine [agility]-Probe (2) ablegen. Falls die Probe misslingt, hebe die Effekte der Bewegung auf.\n[action] Gib 1 [per_investigator] Hinweise aus, als Gruppe: Drehe diese Karte um.",
"11666|text": "[reaction] Nachdem du den letzten Hinweis an diesem Ort entdeckst: Du entdeckst diese Glyphe:\n[tdc_rune_c]\nNotiere in deinem Kampagnenlogbuch „Älteres Wesen“ unter [tdc_rune_c] im Glyphenprotokoll. Diese Glyphe wurde übersetzt.",
"11681|text": "<b>Erzwungen</b> - Wenn Cthulhu diesen Ort betritt: Jeder Ermittler legt 1 zufällige Karte von seiner Hand ab.\n[action]: Lege eine [willpower]-Probe (5) ab. Falls die Probe gelingt, lege 1 Verderben auf die Obsidianklaue. Ermittler an diesem Ort dürfen als Gruppe 1 [per_investigator] Hinweise ausgeben, um 1 weiteres Verderben auf die Obsidianklaue zu legen.",
"11682|text": "<b>Erzwungen</b> - Wenn Cthulhu diesen Ort betritt: Jeder Ermittler erleidet 1 direkten Horror.\n[action]: Lege eine [intellect]-Probe (5) ab. Falls die Probe gelingt, lege 1 Verderben auf die Gezeitentafel. Ermittler an diesem Ort dürfen als Gruppe 1 [per_investigator] Hinweise ausgeben, um 1 weiteres Verderben auf die Gezeitentafel zu legen.",
"11683|text": "[action] Ermittler an deinem Ort geben 1 [per_investigator] Hinweise aus, als Gruppe: Ziehe die oberste Karte unter deinem Ort. Falls es sich um einen Vorteil handelt, übernimm die Kontrolle über ihn.",
"11713|text": "Falls sich keine [[Cthulhu]]-Gegner auf dem Siegespunktestapel befinden, lege diese Karte ab und ziehe die oberste Karte des Cthulhu-Decks.\nWähle andernfalls einen Ermittler, der eine [willpower]-Probe (X) ablegt, wobei X Cthulhus Zorn ist. Falls die Probe misslingt, wähle einen [[Cthulhu]]-Gegner auf dem Siegespunktestapel und bringe ihn mit seiner <b>Erzürnt</b>-Seite nach oben auf das Cthulhu-Brett zurück.",
"11714|text": "Senke die Flutstufe des Ortes von Cthulhu und wähle einen anderen Ort <i>(mit einem Ermittler, falls möglich)</i>, dessen Flutstufe erhöht werden kann. Erhöhe die Flutstufe des gewählten Ortes.\nJeder Ermittler an einem völlig überfluteten Ort legt eine [agility]-Probe (X) ab, wobei X Cthulhus Zorn ist. Falls die Probe misslingt, muss der Ermittler entweder 1 Schaden erleiden oder einen Nicht-Story-Vorteil ablegen, den er kontrolliert.",
"11721|text": "Zurückhaltend. Patrouille (nächster anderer Gegner ohne Verderben auf ihm).\n<b>Erzwungen</b> - Wenn die Gegnerphase endet: Lege 1 Verderben auf einen anderen Nicht-[[Elite]]-Gegner an diesem Ort. Lege dann den Blindepassagier-Drohnen ab.",
"11762|text": "Anwendungen (3 Vorräte).\n[action] Gib 1 Vorrat aus: Heile 1 Horror von einem Ermittler an deinem Ort.\n[reaction] Wenn du eine Nicht-Schwäche-[[Kraft]]- oder [[Schrecken]]-Verratskarte ziehst, entferne Laudanum aus dem Spiel: Annulliere den Enthüllungseffekt jener Verratskarte und lege sie ab."
}
json.dump(fixes, open('/tmp/tdc_extra_fixes3.json','w'), ensure_ascii=False, indent=1)
print('written', len(fixes))
