import json
fixes = {
"11557|text": "Jäger.\n<b>Erscheinen</b> - Mit Beute in einen Kampf verwickelt.\n<b>Beute</b> - Meiste Hinweise.\nWenn sich der Gewölbediener über seinen Jäger-Schlüsselwort bewegt, gilt sein Ort als mit jedem aktivierten Ort verbunden.",
"11559b|text": "Du darfst den ersten Angriff ignorieren, der dich in jeder Runde durch einen [[Sternengezücht]]- oder [[Tiefes Wesen]]-Gegner trifft.\n[tdc_rune_b] · [tdc_rune_x] · [tdc_rune_o] · [tdc_rune_k]\n[reaction] Wenn ein [[Sternengezücht]]- oder [[Tiefes Wesen]]-Gegner deinen Ort betritt, erschöpfe diese Karte: Mache jenen Gegner erschöpft.",
"11573|text": "Erzwungen - Wenn du Andere Weltliche Mechanismen enthüllst: Ziehe 1 zufällige beiseitegelegte [[Glyphe]]-Verratskarte, falls möglich.\n[action] Lege 1 Schaden und 1 Horror: Aktiviere diesen Ort.",
"11577|text": "<b>Enthüllung</b> - Lege eine [willpower]-Probe (3) ab. Falls die Probe misslingt, musst du entscheiden (wähle eins; wähle zwei stattdessen, falls es Szene 2 ist):\n- Deaktiviere den nächstgelegenen aktivierten [[Gewölbe]]-Ort.\n- Ziehe 1 der beiseitegelegten Gewölbediener-Gegner.\n- Bewege dich zu einem angrenzenden Ort (überflutet, falls möglich).",
"11612|text": "Leicht / Standard\n[skull]: -X. X ist die Anzahl der [[Glyphe]]-Karten auf dem Siegespunktestapel.\n[cultist]: -2 (stattdessen -4, falls sich ein [[Blinder Passagier]]-Gegner an deinem Ort befindet).\n[tablet]: -2. Falls dein Ort überflutet ist, enthülle einen weiteren Marker.\n[elder_thing]: -4. Falls dieser Marker während eines Kampf- oder Ausweichversuchs enthüllt wird, erleide 1 Schaden oder 1 Horror.",
"11626|text": "Jeder [[Sternengezücht]]-Gegner verliert Patrouille sowie seine aufgedruckten <b>Beute</b>-Anweisungen und erhält Jäger sowie „<b>Beute</b> - Du.“\n[tdc_rune_u] · [tdc_rune_x] · [tdc_rune_o] · [tdc_rune_o] · [tdc_rune_d] · [tdc_rune_f] · [tdc_rune_z]\n[fast] Erschöpfe Horror in Ton: Behandle entweder das aufgedruckte Textfeld dieses Vorteils bis zum Ende der Runde, als ob es leer wäre <i>(mit Ausnahme der [[Merkmale]])</i>, oder bewege einen [[Sternengezücht]]-Gegner einmal in eine beliebige Richtung.",
"11639|text": "Leicht / Standard\n[skull]: -X. X ist die aktuelle Sturmintensität.\n[cultist]: -4. Falls diese Probe misslingt, lege 1 Verderben auf den nächstgelegenen Gegner.\n[tablet]: -1 für jeden offenen Himmel, der an deinen aktuellen Ort angrenzt.\n[elder_thing]: -2. Falls sich ein Gegner an deinem Ort befindet, enthülle einen weiteren Marker.",
"11640|text": "<b>Erzwungen</b> - Wenn die Runde endet, enthülle so viele Marker aus dem Chaosbeutel, wie die Sturmintensität beträgt. Falls ein Nicht-[elder_sign]-Symbolmarker enthüllt wird:\n- Mische die rechten offenen Himmel/[[Gipfel]]-Orte in den Reihen 2 und 4 und lege sie oben auf das Gipfeldeck <i>(oder lege sie stattdessen auf den Siegespunktestapel, falls sie <b>Sieg X</b> und keine Hinweise auf ihnen haben)</i>. Jeder Gegner, jeder Marker und jedes Anhängsel an diesen Orten/offenen Himmeln wird abgelegt.\n- Schiebe jeden offenen Himmel und jeden [[Gipfel]]-Ort in den Reihen 2 und 4 einmal nach rechts.\n- Lege die unterste Karte des Gipfeldecks in jede so entstandene Lücke.\n- Drehe diese Karte um.",
"11640b|text": "<b>Erzwungen</b> - Wenn die Runde endet, enthülle so viele Marker aus dem Chaosbeutel, wie die Sturmintensität beträgt. Falls ein Nicht-[elder_sign]-Symbolmarker enthüllt wird:\n- Mische die rechten offenen Himmel/[[Gipfel]]-Orte in den Reihen 2 und 4 und lege sie oben auf das Gipfeldeck <i>(oder lege sie stattdessen auf den Siegespunktestapel, falls sie <b>Sieg X</b> und keine Hinweise auf ihnen haben)</i>. Jeder Gegner, jeder Marker und jedes Anhängsel an diesen Orten/offenen Himmeln wird abgelegt.\n- Schiebe jeden offenen Himmel und jeden [[Gipfel]]-Ort in den Reihen 2 und 4 einmal nach rechts.\n- Lege die unterste Karte des Gipfeldecks in jede so entstandene Lücke.\n- Drehe diese Karte um.",
"11647|text": "[action] Gib X Hinweise aus: Enthülle X Karten von der Unterseite des Gipfeldecks. Du darfst 1 enthüllten Ort in einem angrenzenden offenen Himmel ins Spiel bringen und dich dorthin bewegen. <i>(Lege jene Himmelskarte und jede andere enthüllte Karte in beliebiger Reihenfolge oben auf das Gipfeldeck zurück.)</i>\n<b>Ziel</b> - Falls jeder überlebende Ermittler aufgegeben hat, rücke vor.",
"11648|text": "Die Straßen von R'lyeh können nicht bewegt werden und können das Spiel nicht verlassen.\n[action] Gib 1-3 Ressourcen aus: Lege entsprechend viele Hinweise <i>(aus dem Markervorrat)</i> auf einen beliebigen enthüllten Ort. (Nur ein Mal pro Runde.)",
"11649|text": "<b>Erzwungen</b> - Nachdem du diesen Ort enthüllst: Lege eine [agility]-Probe (1) ab. Falls die Probe misslingt, durchsuche das Begegnungsdeck und den Ablagestapel nach einem [[Monster]]-Gegner und erschaffe ihn, mit dir in einen Kampf verwickelt.\n[action]: Bringe das beiseitegelegte Himmelsrelikt [tdc_rune_f] unter deiner Kontrolle ins Spiel.",
"11662|text": "Falls das Glyphen-Planetarium [tdc_rune_d] das Spiel verlassen würde, lege es beiseite, außerhalb des Spiels <i>(oder auf den Siegespunktestapel, falls sich keine Hinweise auf ihm befinden)</i>.\n<b>Erzwungen</b> - Wenn du diesen Ort betreten würdest und du die Obsidianklaue nicht kontrollierst: Du musst entweder 1 Hinweis ausgeben oder eine [agility]-Probe (2) ablegen. Falls die Probe misslingt, hebe die Effekte der Bewegung auf.\n[action] Gib 1 [per_investigator] Hinweise aus, als Gruppe: Drehe diese Karte um.",
"11666|text": "<b>Enthüllung</b> - Lege eine [willpower]-Probe (1) ab. Diese Probe bekommt +1 Schwierigkeit für jeden offenen Himmel, der an deinen Ort angrenzt. Für jeden Punkt, um den die Probe misslingt, musst du entweder 1 Aktion verlieren oder 1 Horror erleiden.",
"11667|text": "<b>Enthüllung</b> - Bringe Schwingen des Schreckens in deiner Bedrohungszone ins Spiel.\n<b>Erzwungen</b> - Nachdem du eine Fertigkeitsprobe misslingst: Lege Karten von der Oberseite des Begegnungsdecks ab, bis ein Gegner abgelegt wird. Ziehe entweder jenen Gegner, oder er greift dich an <i>(aus dem Ablagestapel)</i>. Lege dann Schwingen des Schreckens ab.",
"11681|text": "<b>Erzwungen</b> - Wenn Cthulhu diesen Ort betritt: Jeder Ermittler legt 1 zufällige Karte von seiner Hand ab.\n[action]: Lege eine [willpower]-Probe (5) ab. Falls die Probe gelingt, lege 1 Verderben auf die Obsidianklaue. Ermittler an diesem Ort dürfen als Gruppe 1 [per_investigator] Hinweise ausgeben, um 1 weiteres Verderben auf die Obsidianklaue zu legen.",
"11682|text": "Leicht / Standard\n[skull]: -X. X ist die Hälfte der Anzahl der Orte ohne Szenenkarten darunter (aufgerundet).\n[cultist]: -3. Falls diese Probe misslingt, lege 1 Verderben auf den nächstgelegenen Gegner ohne Verderben auf ihm.\n[tablet]: -3. Falls diese Probe misslingt, lege 1 deiner Hinweise auf deinen Ort.\n[elder_thing]: -2. Falls dein Ort überflutet ist, enthülle einen weiteren Marker.",
"11683|text": "[action]: <b>Aufgeben.</b> Du gibst deine Suche auf.\n<b>Erzwungen -</b> Wenn Verderben auf diese Agenda gelegt wird: Erhöhe die Flutstufe des Ortes des führenden Ermittlers.",
"11688|text": "Jeder [[Sternengezücht]]-Gegner verliert Patrouille sowie seine aufgedruckten <b>Beute</b>-Anweisungen und erhält Jäger sowie „<b>Beute</b> - Du.“\n[tdc_rune_u] · [tdc_rune_x] · [tdc_rune_o] · [tdc_rune_o] · [tdc_rune_d] · [tdc_rune_f] · [tdc_rune_z]\n[fast] Erschöpfe Horror in Ton: Behandle entweder das aufgedruckte Textfeld dieses Vorteils bis zum Ende der Runde, als ob es leer wäre <i>(mit Ausnahme der [[Merkmale]])</i>, oder bewege einen [[Sternengezücht]]-Gegner einmal in eine beliebige Richtung.",
"11713|text": "Falls sich keine [[Cthulhu]]-Gegner auf dem Siegespunktestapel befinden, lege diese Karte ab und ziehe die oberste Karte des Cthulhu-Decks.\nWähle andernfalls einen Ermittler, der eine [willpower]-Probe (X) ablegt, wobei X Cthulhus Zorn ist. Falls die Probe misslingt, wähle einen [[Cthulhu]]-Gegner auf dem Siegespunktestapel und bringe ihn mit seiner [[Erzürnt]]-Seite nach oben auf das Cthulhu-Brett zurück.",
"11714|text": "Senke die Flutstufe des Ortes von Cthulhu und wähle einen anderen Ort <i>(mit einem Ermittler, falls möglich)</i>, dessen Flutstufe erhöht werden kann. Erhöhe die Flutstufe des gewählten Ortes.\nJeder Ermittler an einem völlig überfluteten Ort legt eine [agility]-Probe (X) ab, wobei X Cthulhus Zorn ist. Falls die Probe misslingt, muss der Ermittler entweder 1 Schaden erleiden oder einen Nicht-Story-Vorteil ablegen, den er kontrolliert."
}
json.dump(fixes, open('/tmp/tdc_extra_fixes4.json','w'), ensure_ascii=False, indent=1)
print('written', len(fixes))
