import json
fixes = {
"11573|text": "Gewaltig. Erbarmungslos.\n<b>Erzwungen</b> - Wenn ein anderer [[Blinder Passagier]]-Gegner besiegt wird: Bewege allen Schaden von jenem Gegner auf die Mutter. (Falls sich Verderben auf jenem Gegner befand, mische ihn ebenfalls in das Begegnungsdeck zurück.)",
"11640|text": "<b>Erzwungen</b> - Wenn die Runde endet, enthülle so viele Marker aus dem Chaosbeutel, wie die Sturmintensität beträgt. Falls ein Nicht-[elder_sign]-Symbolmarker enthüllt wird:\n- Mische die rechten offenen Himmel/[[Gipfel]]-Orte in den Reihen 2 und 4 und lege sie oben auf das Gipfeldeck (oder lege sie stattdessen auf den Siegespunktestapel, falls sie <b>Sieg X</b> und keine Hinweise auf ihnen haben). Jeder Gegner, jeder Marker und jedes Anhängsel an diesen Orten/offenen Himmeln wird abgelegt.\n- Schiebe jeden offenen Himmel und jeden [[Gipfel]]-Ort in den Reihen 2 und 4 einmal nach rechts.\n- Lege die unterste Karte des Gipfeldecks in jede so entstandene Lücke.\n- Drehe diese Karte um.",
"11640b|text": "<b>Erzwungen</b> - Wenn die Runde endet, enthülle so viele Marker aus dem Chaosbeutel, wie die Sturmintensität beträgt. Falls ein Nicht-[elder_sign]-Symbolmarker enthüllt wird:\n- Mische die rechten offenen Himmel/[[Gipfel]]-Orte in den Reihen 2 und 4 und lege sie oben auf das Gipfeldeck (oder lege sie stattdessen auf den Siegespunktestapel, falls sie <b>Sieg X</b> und keine Hinweise auf ihnen haben). Jeder Gegner, jeder Marker und jedes Anhängsel an diesen Orten/offenen Himmeln wird abgelegt.\n- Schiebe jeden offenen Himmel und jeden [[Gipfel]]-Ort in den Reihen 2 und 4 einmal nach rechts.\n- Lege die unterste Karte des Gipfeldecks in jede so entstandene Lücke.\n- Drehe diese Karte um.",
"11662|text": "Falls das Glyphen-Planetarium [tdc_rune_d] das Spiel verlassen würde, lege es beiseite, außerhalb des Spiels (oder auf den Siegespunktestapel, falls sich keine Hinweise auf ihm befinden).\n<b>Erzwungen</b> - Wenn du diesen Ort betreten würdest und du die Obsidianklaue nicht kontrollierst: Du musst entweder 1 Hinweis ausgeben oder eine [agility]-Probe (2) ablegen. Falls die Probe misslingt, hebe die Effekte der Bewegung auf.\n[action] Gib 1 [per_investigator] Hinweise aus, als Gruppe: Drehe diese Karte um.",
"11667|text": "<b>Enthüllung</b> - Bringe Schwingen des Schreckens in deiner Bedrohungszone ins Spiel.\n<b>Erzwungen</b> - Nachdem du eine Fertigkeitsprobe misslingst: Lege Karten von der Oberseite des Begegnungsdecks ab, bis ein Gegner abgelegt wird. Ziehe entweder jenen Gegner, oder er greift dich an (aus dem Ablagestapel). Lege dann Schwingen des Schreckens ab.",
"11681|text": "<b>Erzwungen</b> - Wenn Cthulhu diesen Ort betritt: Jeder Ermittler entfernt die oberste Karte seines Decks aus dem Spiel.\n[action] Gib 1 [per_investigator] Hinweise aus: Lege 1 Verderben auf den Splitter von Y'ch'lecht. Ermittler an diesem Ort dürfen als Gruppe 1 [per_investigator] Hinweise ausgeben, um 1 weiteres Verderben auf den Splitter von Y'ch'lecht zu legen.",
"11688|text": "Jeder [[Sternengezücht]]-Gegner verliert Patrouille sowie seine aufgedruckten <b>Beute</b>-Anweisungen und erhält Jäger sowie „<b>Beute</b> - Du.“\n[tdc_rune_u] · [tdc_rune_x] · [tdc_rune_o] · [tdc_rune_o] · [tdc_rune_d] · [tdc_rune_f] · [tdc_rune_z]\n[fast] Erschöpfe Horror in Ton: Behandle entweder das aufgedruckte Textfeld dieses Vorteils bis zum Ende der Runde, als ob es leer wäre (mit Ausnahme der Merkmale), oder bewege einen [[Sternengezücht]]-Gegner einmal in eine beliebige Richtung.",
"11714|text": "Senke die Flutstufe des Ortes von Cthulhu und wähle einen anderen Ort (mit einem Ermittler, falls möglich), dessen Flutstufe erhöht werden kann. Erhöhe die Flutstufe des gewählten Ortes.\nJeder Ermittler an einem völlig überfluteten Ort legt eine [agility]-Probe (X) ab, wobei X Cthulhus Zorn ist. Falls die Probe misslingt, muss der Ermittler entweder 1 Schaden erleiden oder einen Nicht-Story-Vorteil ablegen, den er kontrolliert."
}
json.dump(fixes, open('/tmp/tdc_extra_fixes6.json','w'), ensure_ascii=False, indent=1)
print('written', len(fixes))
