T = {
"11733|text": "Jäger.\n<b>Beute</b> - Meiste Hinweise.\nSolange sich der Voltaische Aal während der Gegnerphase bewegt, ist jeder völlig überflutete Ort als mit jedem anderen verbunden zu betrachten.",
"11734|text": "<b>Enthüllung</b> - Falls sich keine Gegner im Spiel befinden, erhält Träumende Wanderung Schwall. Lege andernfalls eine [willpower]-Probe (3) ab. Falls du misslingst, musst du eins wählen:\n- Der nächstgelegene Gegner bewegt sich zu deinem Ort und führt sofort einen Angriff durch.\n- Ziehe den obersten Gegner im Ablagestapel des Begegnungsdecks.",
"11735|text": "<b>Enthüllung</b> - Lege eine [agility]-Probe (3) ab. Diese Probe bekommt +2 Schwierigkeit, falls dein Ort völlig überflutet ist. Falls du misslingst, nimm 1 Schaden und erhöhe die Flutstufe des nächstgelegenen geeigneten Ortes.",
"11736|text": "<b>Enthüllung</b> - Falls dein Ort nicht überflutet ist, erhält Tödlicher Schwall Schwall. Andernfalls musst du wählen:\n- Lege eine [agility]-Probe (4) ab, um dich in Sicherheit zu schwimmen. Falls du gelingst, bewege dich zu einem verbundenen Ort. Falls du misslingst, nimm 1 Schaden und 1 Horror.\n- Lege eine [combat]-Probe (4) ab, um zu halten, was dir gehört. Falls du misslingst, nimm 1 Schaden und lege 1 Vorteil ab, den du kontrollierst und der 1 oder mehr Handplätze belegt.",
"11737|text": "Schwall.\n<b>Enthüllung</b> - Erhöhe die Flutstufe des nächstgelegenen geeigneten Ortes.",
"11738|text": "<b>Enthüllung</b> - Bringe Omenhafte Stille in deiner Bedrohungszone ins Spiel.\nAls zusätzliche Kosten, um eine Karte zu spielen, musst du entweder 1 Ressource ausgeben oder 1 Horror nehmen.\n[action]: Lege eine [agility]-Probe (3) ab. Falls dein Ort nicht überflutet ist, gelingt diese Probe automatisch. Falls die Probe gelingt, lege Omenhafte Stille ab.",
"11739|text": "<b>Enthüllung</b> - Lege eine [intellect]-Probe (X) ab, wobei X der aufgedruckte Schleierwert deines Ortes ist. Für jeden Punkt, um den du misslingst, wähle 1 Karte von deiner Hand und lege sie ab (maximal 3).",
"11740|text": "<b>Enthüllung</b> - Lege eine [agility]-Probe (X) ab, wobei X der aufgedruckte Schleierwert deines Ortes ist. Falls du misslingst, nimm 2 Schaden.",
"11741|text": "<b>Enthüllung</b> - Lege eine [combat]-Probe (3) ab. Falls du misslingst, musst du entweder 2 Horror nehmen oder einem Ermittler an deinem Ort 1 direkten Schaden zufügen.",
"11742|text": "<b>Enthüllung</b> - Lege eine [willpower]-Probe (X) ab, wobei X der aufgedruckte Schleierwert deines Ortes ist. Falls du misslingst, nimm 2 Horror.",
"11743|text": "Wagnis.\n<b>Enthüllung</b> - Du musst entscheiden (wähle eins):\n- Lege 1 Verderben auf die aktuelle Agenda. Durch diesen Effekt kann die aktuelle Agenda vorrücken.\n- Jeder Ermittler legt 2 Karten von seiner Hand ab.\n- Jeder Ermittler verliert 1 Aktion.",
"11744|subname": "Unermüdlicher Verfolger",
"11744|text": "Jäger. Erbarmungslos.\n<b>Erscheinen</b> - Beliebiger verbundener Ort <i>(leer, falls möglich)</i>.\n<b>Erzwungen</b> - Das erste Mal in jeder Runde, wenn ein [elder_thing]-Marker aus dem Chaosbeutel enthüllt wird: Mache das Unausweichliche spielbereit und handle sein Jäger-Schlüsselwort ab <i>(es greift nicht an)</i>.",
"11745|text": "<b>Enthüllung</b> - Lege eine [agility]-Probe (2) ab. Diese Probe bekommt +1 Schwierigkeit für jede Kopie von Immer noch hinter dir im Siegespunktestapel. Falls du misslingst und das Unausweichliche ...\n- ... im Spiel ist, bewegt es sich, einen Ort nach dem anderen, zu deinem Ort und verbindet sich mit dir im Kampf.\n- ... nicht im Spiel ist, durchsuche alle im- und außerhalb des Spiels befindlichen Bereiche nach dem Unausweichlichen und ziehe es. Füge Immer noch hinter dir dem Siegespunktestapel hinzu.",
"11746|text": "<b>Erzwungen</b> - Nachdem der Tiefes-Wesen-Sklave sich mit dir im Kampf verbindet: Lege 1 zufällige Karte von deiner Hand ab.",
"11747|text": "Jäger. Zurückschlagen.\nJeder andere [[Tiefes Wesen]]-Gegner erhält Erbarmungslos.\n<b>Erzwungen</b> - Nachdem der Ältere Tiefes-Wesen sich mit dir im Kampf verbindet: Heile 1 Schaden von jedem anderen [[Tiefes Wesen]]-Gegner im Spiel.",
"11748|text": "<b>Enthüllung</b> - Bringe Hinterhalt der Tiefen Wesen in deiner Bedrohungszone ins Spiel. Nur 1 pro Ermittler.\n<b>Erzwungen</b> - Nachdem sich ein [[Tiefes Wesen]]-Gegner mit dir im Kampf verbindet: Greift er dich an. Lege dann Hinterhalt der Tiefen Wesen ab.",
"11749|text": "<b>Enthüllung</b> - Lege eine [willpower]-Probe (3) ab. Diese Probe bekommt +2 Schwierigkeit, falls du 3 oder weniger Karten auf der Hand hast. Falls du misslingst, nimm 1 direkten Horror und lege 1 zufällige Karte von deiner Hand ab.",
"11750|text": "<b>Enthüllung</b> - Bringe Zur Dunkelheit hingezogen in deiner Bedrohungszone ins Spiel. Nur 1 pro Ermittler.\nDein Handkartenlimit wird um 3 gesenkt (mindestens 1).\n<b>Erzwungen</b> - Wenn dein Zug endet, falls du keine Karten auf der Hand hast: Lege Zur Dunkelheit hingezogen ab.",
"11751|text": "Jäger.\n<b>Beute</b> - Nächstgelegener Ermittler mit einer [[Artefakt]]-Vorteilskarte.\n<b>Erzwungen</b> - Wenn du diesen Gegner besiegt: Erschaffe jeden anderen Hartnäckiges Konstrukt im Siegespunktestapel, erschöpft, an deinem Ort.",
"11752|text": "<b>Enthüllung</b> - Bringe Höllische Maschinerie in deiner Bedrohungszone ins Spiel.\nDu kannst keine Fähigkeiten auf [[Glyphe]]- oder [[Artefakt]]-Karten auslösen.\n[action]: Lege eine [intellect]- oder [agility]-Probe (4) ab. Falls die Probe gelingt, lege Höllische Maschinerie ab.",
"11753a|subname": "Verloren und unsicher",
"11753a|text": "Dauerhaft. Anwendungen (8 Entdeckungen).\n<b>Erzwungen</b> - Wenn du einen Ort enthüllst oder einen Ort ins Spiel bringst: Entferne 1 Entdeckung von Kein Ort wie zu Hause.\n<b>Erzwungen</b> - Wenn das Spiel endet, falls sich 1 [per_investigator] oder weniger Entdeckungen auf Kein Ort wie zu Hause befinden: Vermerke in deinem Kampagnenlogbuch 1 Fortschritt unter dieser Aufgabe.",
"11753b|subname": "Wo dein Herz schlägt",
"11753b|text": "Dauerhaft. Falls diese Aufgabe nicht abgeschlossen ist, kommt sie mit ihrer Schwäche-Seite nach oben ins Spiel.\nDu darfst während deines Zuges eine zusätzliche Aktion nehmen, die nur für eine Bewegung verwendet werden kann.",
"11754a|subname": "Blindes Gottvertrauen",
"11754a|text": "Dauerhaft. Anwendungen (0 Zeichen).\n[reaction] Nachdem ein [elder_sign]-Marker an einem beliebigen Ort enthüllt wurde: Lege 1 Zeichen auf Wandel im Glauben.\n<b>Erzwungen</b> - Wenn das Spiel endet, falls sich mehr als 1 [per_investigator] Zeichen auf Wandel im Glauben befinden: Vermerke in deinem Kampagnenlogbuch 1 Fortschritt unter dieser Aufgabe.",
"11754b|subname": "Erfüllt von Geist",
"11754b|text": "Dauerhaft. Falls diese Aufgabe nicht abgeschlossen ist, kommt sie mit ihrer Schwäche-Seite nach oben ins Spiel.\nDu bekommst +1 [willpower].\n[reaction] Nachdem ein [elder_sign]-Marker an einem beliebigen Ort enthüllt wurde: Heile 1 Horror von einem Ermittler an jenem Ort.",
"11755a|subname": "Verleugnet und entehrt",
"11755a|text": "Dauerhaft.\n<b>Erzwungen</b> - Wenn du 1 oder mehr Schaden nimmst: Lege 1 Schaden auch auf Auf der Linie.\n<b>Erzwungen</b> - Wenn das Spiel endet, falls die Menge an Schaden auf dieser Karte deiner maximalen Gesundheit entspricht oder sie übersteigt: Vermerke in deinem Kampagnenlogbuch 1 Fortschritt unter dieser Aufgabe.",
"11755b|subname": "Wiederhergestellt und entschlossen",
"11755b|text": "Dauerhaft. Falls diese Aufgabe nicht abgeschlossen ist, kommt sie mit ihrer Schwäche-Seite nach oben ins Spiel.\nDu bekommst +1 [combat] und +2 maximale Gesundheit.",
"11756a|subname": "Das „Quid“",
"11756a|text": "Dauerhaft.\n[reaction] Wenn du 1 oder mehr Ressourcen erhältst: Lege 1 dieser Ressourcen auf Gutes Geld.\n<b>Erzwungen</b> - Wenn das Spiel endet, falls sich 5 oder mehr Ressourcen auf Gutes Geld befinden: Vermerke in deinem Kampagnenlogbuch 1 Fortschritt unter dieser Aufgabe.",
"11756b|subname": "Das „Quo“",
"11756b|text": "Dauerhaft. Falls diese Aufgabe nicht abgeschlossen ist, kommt sie mit ihrer Schwäche-Seite nach oben ins Spiel.\nDu beginnst das Spiel mit 5 zusätzlichen Ressourcen.",
"11757a|subname": "Bist du eine Last?",
"11757a|text": "Dauerhaft. Anwendungen (4 Gelegenheiten).\n<b>Erzwungen</b> - Nachdem du eine Fertigkeitsprobe um 2 oder mehr misslingst: Entferne 1 Gelegenheit von Beweise deinen Wert.\n<b>Erzwungen</b> - Wenn das Spiel endet, falls sich 1 oder mehr Gelegenheiten auf Beweise deinen Wert befinden: Vermerke in deinem Kampagnenlogbuch 1 Fortschritt unter dieser Aufgabe.",
"11757b|subname": "Auf eigenen Beinen",
"11757b|text": "Dauerhaft. Falls diese Aufgabe nicht abgeschlossen ist, kommt sie mit ihrer Schwäche-Seite nach oben ins Spiel.\nAnwendungen (3 Gelegenheiten).\n[reaction] Wenn ein Nicht-[auto_fail]-Marker während einer Fertigkeitsprobe an deinem Ort enthüllt wird, gib 1 Gelegenheit aus: Hebe jenen Marker auf.",
"11758a|subname": "Kannst du sie retten?",
"11758a|text": "Dauerhaft. Anwendungen (5 Verpflichtungen).\n[reaction] Nachdem du Schaden/Horror von einem Ermittler oder einer [[Verbündeter]]-Vorteilskarte heilst: Entferne 1 Verpflichtung von Kein Leid zufügen.\n<b>Erzwungen</b> - Wenn das Spiel endet, falls sich keine Verpflichtungen auf Kein Leid zufügen befinden: Vermerke in deinem Kampagnenlogbuch 1 Fortschritt unter dieser Aufgabe.",
"11758b|subname": "Verlässliche Unterstützung",
"11758b|text": "Dauerhaft. Falls diese Aufgabe nicht abgeschlossen ist, kommt sie mit ihrer Schwäche-Seite nach oben ins Spiel.\nDu bekommst +1 [agility].\n[reaction] Nachdem du Schaden/Horror von einem Ermittler oder einer [[Verbündeter]]-Vorteilskarte heilst, erschöpfe Kein Leid zufügen: Erhalte 1 Ressource.",
"11759a|subname": "Visionen einer düsteren Zukunft",
"11759a|text": "Dauerhaft.\n<b>Erzwungen</b> - Wenn du 1 oder mehr Horror nimmst: Lege 1 Horror auch auf Träume der Zerstörung.\n<b>Erzwungen</b> - Wenn das Spiel endet, falls die Menge an Horror auf dieser Karte deiner maximalen geistigen Gesundheit entspricht oder sie übersteigt: Vermerke in deinem Kampagnenlogbuch 1 Fortschritt unter dieser Aufgabe.",
"11759b|subname": "Die Zukunft ist nicht geschrieben",
"11759b|text": "Dauerhaft. Falls diese Aufgabe nicht abgeschlossen ist, kommt sie mit ihrer Schwäche-Seite nach oben ins Spiel.\nDu hast 1 zusätzlichen Arkanum-Handplatz und bekommst +2 maximale geistige Gesundheit.",
"11760a|subname": "Zwanghafte Forschung",
"11760a|text": "Dauerhaft. Anwendungen (5 Besessenheiten).\n<b>Erzwungen</b> - Nachdem du den letzten verbliebenen Hinweis an deinem Ort entdeckt hast: Entferne 1 Besessenheit von Erforsche die Tiefen.\n<b>Erzwungen</b> - Wenn das Spiel endet, falls sich keine Besessenheiten auf Erforsche die Tiefen befinden: Vermerke in deinem Kampagnenlogbuch 1 Fortschritt unter dieser Aufgabe.",
"11760b|subname": "Meisterhaftes Wissen",
"11760b|text": "Dauerhaft. Falls diese Aufgabe nicht abgeschlossen ist, kommt sie mit ihrer Schwäche-Seite nach oben ins Spiel.\nDu bekommst +1 [intellect].\n[reaction] Nachdem du den letzten Hinweis an deinem Ort entdeckt hast, erschöpfe Erforsche die Tiefen: Ziehe 1 Karte.",
"11761|subname": "Zäh, aber verlässlich",
"11761|text": "Anwendungen (3 Vorräte).\n[action] Gib 1 Vorrat aus: Heile 1 Schaden von einem Ermittler an deinem Ort.\n[fast] Entferne Expeditionsausrüstung aus dem Spiel: Bewege einen Nicht-[[Elite]]-Gegner an deinem Ort oder an einem verbundenen Ort einmal in eine beliebige Richtung.",
"11762|subname": "Verzweifelte Maßnahmen",
"11762|text": "Anwendungen (3 Vorräte).\n[action] Gib 1 Vorrat aus: Heile 1 Horror von einem Ermittler an deinem Ort.\n[reaction] Wenn du eine Nicht-Schwäche-[[Kraft]]- oder [[Schrecken]]-Verratskarte ziehst, entferne Laudanum aus dem Spiel: Hebe den Enthüllungseffekt jener Verratskarte auf und lege sie ab.",
"11763|subname": "Vorsintflutliche Schriften",
"11763|text": "Anwendungen (4 Geheimnisse).\n[fast] Während einer Fertigkeitsprobe auf einer [[Glyphe]]- oder [[R'lyeh]]-Karte, erschöpfe die Fremdartige Tafel und gib 1 Geheimnis aus: Der abhandelnde Ermittler bekommt +2 Fertigkeitswert für diese Fertigkeitsprobe.",
"11764|text": "Falls dein Ort völlig überflutet ist, darfst du ihn im Hinblick auf Karteneffekte behandeln, als ob er teilweise überflutet wäre.\n<b>Erzwungen</b> - Wenn beliebige Mengen an Schaden auf dich gelegt werden würden: Lege 1 davon auf den Taucheranzug.",
"11765|subname": "Meisterdiebin",
"11765|text": "Du bekommst +1 [agility].\n[fast] Falls sich keine spielbereiten Gegner an deinem Ort befinden, erschöpfe Ruby Standish: Bewege dich zu einem verbundenen Ort.",
"11766|subname": "Ehrgeizige Journalistin",
"11766|text": "Du bekommst +1 [intellect].\nFalls sich keine Hinweise auf deinem Ort befinden, ignoriere den ersten Gelegenheitsangriff gegen dich in jeder Runde.",
}
